# Generated by Django 5.0.14 on 2026-09-15 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MAKER", "Maker"),
                            ("CHECKER", "Checker"),
                            ("CERTIFIER", "Certifier"),
                            ("SUPERADMIN", "Superadmin"),
                            ("MEMBER", "Member"),
                            ("BOARD", "Board"),
                            ("AUDITOR", "Auditor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("must_change_password", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["role", "user__username"],
                "indexes": [
                    models.Index(fields=["role"], name="users_userp_role_c31a7e_idx")
                ],
            },
        ),
    ]
