# Generated by Django 5.0.14 on 2026-09-15 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
        ("users", "0002_seed_superadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionpipelineactor",
            name="certifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certified_pipeline_actors",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="transactionpipelineactor",
            name="checker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checked_pipeline_actors",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="transactionpipelineactor",
            name="maker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="made_pipeline_actors",
                to="users.userprofile",
            ),
        ),
    ]
