# Generated by Django 5.0.14 on 2026-09-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_alter_transactionpipelineactor_certifier_and_more"),
        ("users", "0002_seed_superadmin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionpipelineactor",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="transactionpipelineactor",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="transactionpipelineactor",
            name="maker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="made_pipeline_actors",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="transactionpipelineactor",
            name="target_record_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="transactionpipelineactor",
            name="transaction_type",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name="transactionpipelineactor",
            index=models.Index(
                fields=["status", "transaction_type"],
                name="pipeline_tr_status_a93bfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionpipelineactor",
            index=models.Index(
                fields=["transaction_type", "target_record_id"],
                name="pipeline_tr_transac_6ca0bb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionpipelineactor",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("checker__isnull", True),
                    models.Q(("maker", models.F("checker")), _negated=True),
                    _connector="OR",
                ),
                name="ck_pipeline_maker_ne_checker",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionpipelineactor",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("certifier__isnull", True),
                    models.Q(("maker", models.F("certifier")), _negated=True),
                    _connector="OR",
                ),
                name="ck_pipeline_maker_ne_certifier",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionpipelineactor",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("certifier__isnull", True),
                    ("checker__isnull", True),
                    models.Q(("checker", models.F("certifier")), _negated=True),
                    _connector="OR",
                ),
                name="ck_pipeline_checker_ne_certifier",
            ),
        ),
    ]
