# Generated by Django 5.0.14 on 2026-09-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_alter_transactionpipelineactor_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionpipelineactor",
            name="rejection_acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
