# Generated by Django 5.0.14 on 2026-09-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING_CHECK", "Pending Check"),
                    ("PENDING_CERTIFY", "Pending Certify"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("REVERSED", "Reversed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
