# Generated by Django 5.0.14 on 2026-09-15 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journaltransactionline",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_lines",
                to="members.member",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["status", "entry_date"], name="ledger_jour_status_0e09d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["original_journal_entry"], name="ledger_jour_origina_3403c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journaltransactionline",
            index=models.Index(
                fields=["account_code", "entry_type"],
                name="ledger_jour_account_c038f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journaltransactionline",
            index=models.Index(
                fields=["member", "account_code"], name="ledger_jour_member__56f172_idx"
            ),
        ),
    ]
