# Generated by Django 5.0.14 on 2026-09-19 01:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0004_drop_hold_balance_guard"),
        ("pipeline", "0003_alter_transactionpipelineactor_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReversalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS_TRANSACTION", "Savings Transaction"),
                            ("LOAN_REPAYMENT", "Loan Repayment"),
                            ("EXPENSE", "Expense"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CHECK", "Pending Check"),
                            ("PENDING_CERTIFY", "Pending Certify"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_CHECK",
                        max_length=20,
                    ),
                ),
                (
                    "original_journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal_requests",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "pipeline_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversal_requests",
                        to="pipeline.transactionpipelineactor",
                    ),
                ),
                (
                    "reversal_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversed_from",
                        to="ledger.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="ledger_reve_status_3707f0_idx"
                    ),
                    models.Index(
                        fields=["original_journal_entry"],
                        name="ledger_reve_origina_b92424_idx",
                    ),
                ],
            },
        ),
    ]
