# Generated by Django 5.0.14 on 2026-09-15 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0002_initial"),
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("expense_account_code", models.CharField(max_length=20)),
                ("payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CHECK", "Pending Check"),
                            ("PENDING_CERTIFY", "Pending Certify"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_CHECK",
                        max_length=20,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "pipeline_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="pipeline.transactionpipelineactor",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["expense_account_code", "payment_date"],
                        name="expenses_ex_expense_57857b_idx",
                    )
                ],
            },
        ),
    ]
