# Generated by Django 5.0.14 on 2026-09-19 03:34

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="receipt",
            field=models.FileField(
                blank=True,
                help_text="Photo or PDF of the invoice/receipt. Max 5 MB.",
                null=True,
                upload_to=expenses.models.receipt_upload_path,
            ),
        ),
    ]
