# Generated by Django 5.0.14 on 2026-09-21 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_seed_superadmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILURE", "Login Failure"),
                            ("LOGOUT", "Logout"),
                            ("USER_CREATED", "User Created"),
                            ("USER_DISABLED", "User Disabled"),
                            ("USER_ENABLED", "User Enabled"),
                            ("USER_PASSWORD_RESET", "User Password Reset"),
                            ("USER_UPDATED", "User Updated"),
                            ("MEMBER_LOGIN_CREATED", "Member Login Created"),
                            ("MEMBER_LOGIN_RESET", "Member Login Password Reset"),
                            ("CONFIG_PROPOSED", "Config Change Proposed"),
                            ("CONFIG_CERTIFIED", "Config Change Certified"),
                            ("CONFIG_REJECTED", "Config Change Rejected"),
                            ("MEMBER_EXIT_REQUESTED", "Member Exit Requested"),
                            ("MEMBER_EXIT_COMPLETED", "Member Exit Completed"),
                            ("REVERSAL_REQUESTED", "Reversal Requested"),
                            ("REVERSAL_COMPLETED", "Reversal Completed"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("target_id", models.UUIDField(blank=True, null=True)),
                (
                    "target_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="audit_audit_created_6e540c_idx"
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_audit_action_0c6a84_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_audit_actor_i_1175ab_idx",
                    ),
                ],
            },
        ),
    ]
