# Generated by Django 5.0.14 on 2026-10-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login Success"),
                    ("LOGIN_FAILURE", "Login Failure"),
                    ("LOGOUT", "Logout"),
                    ("USER_CREATED", "User Created"),
                    ("USER_DISABLED", "User Disabled"),
                    ("USER_ENABLED", "User Enabled"),
                    ("USER_PASSWORD_RESET", "User Password Reset"),
                    ("USER_UPDATED", "User Updated"),
                    ("MEMBER_LOGIN_CREATED", "Member Login Created"),
                    ("MEMBER_LOGIN_RESET", "Member Login Password Reset"),
                    ("CONFIG_PROPOSED", "Config Change Proposed"),
                    ("CONFIG_CERTIFIED", "Config Change Certified"),
                    ("CONFIG_REJECTED", "Config Change Rejected"),
                    ("MEMBER_UPDATED", "Member Updated"),
                    ("MEMBER_EXIT_REQUESTED", "Member Exit Requested"),
                    ("MEMBER_EXIT_COMPLETED", "Member Exit Completed"),
                    ("REVERSAL_REQUESTED", "Reversal Requested"),
                    ("REVERSAL_COMPLETED", "Reversal Completed"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
