# Generated by Django 5.0.14 on 2026-09-15 05:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pipeline", "0001_initial"),
        ("users", "0002_seed_superadmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalConfigChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parameter_key", models.CharField(max_length=100)),
                ("proposed_value", models.JSONField()),
                ("effective_from", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_CHECK", "Pending Check"),
                            ("PENDING_CERTIFY", "Pending Certify"),
                            ("CERTIFIED", "Certified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "pipeline_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_changes",
                        to="pipeline.transactionpipelineactor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GlobalConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parameter_key", models.CharField(db_index=True, max_length=100)),
                ("parameter_value", models.JSONField()),
                ("effective_from", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("SUPERSEDED", "Superseded")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="config_changes",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["parameter_key", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["parameter_key", "effective_from"],
                        name="governance__paramet_f05007_idx",
                    )
                ],
            },
        ),
    ]
