# Generated by Django 5.0.14 on 2026-09-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0004_globalconfigchange_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfigchange",
            name="warnings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Non-blocking validation warnings surfaced at propose time.",
            ),
        ),
    ]
