"""
Django settings for kdu project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import sys
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Django 5.0's BaseContext.__copy__ calls object.__copy__, which was removed
# from Python 3.14. Keep the supported Django version working on Python 3.14.
if sys.version_info >= (3, 14):
    from django.template.context import BaseContext

    def _base_context_copy(self):
        duplicate = self.__class__.__new__(self.__class__)
        duplicate.__dict__ = self.__dict__.copy()
        duplicate.dicts = self.dicts[:]
        return duplicate

    BaseContext.__copy__ = _base_context_copy

# ====================================================================
# Paths
# ====================================================================
# BASE_DIR points to the project root (where manage.py lives).
# File is at:  kdu/kdu/settings/base.py
#               ^     ^    ^      ^
#               │     │    │      └── base.py
#               │     │    └── settings/
#               │     └── kdu/  (project package)
#               └── project root
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# ====================================================================
# Environment
# ====================================================================
# Load environment variables from .env
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-+*r4b&xi^#yelqxco^p2g3i)b@r*_s9n90q6*ly5-s!ofa$*iv"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-insecure-change-me")
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# ====================================================================
# Application definition
# ====================================================================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "drf_spectacular",

    # KDU - infrastructure apps
    "core",
    "users",
    "accounting",
    "members",
    "pipeline",
    "ledger",
    "governance",
    "reports",

    # KDU - domain
    "savings",
    "loans",
    "expenses",
    "shu",
]

# ====================================================================
# Middleware
# ====================================================================
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware placed above CommonMiddleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ====================================================================
# URLs / WSGI
# ====================================================================
ROOT_URLCONF = "kdu.urls"
WSGI_APPLICATION = "kdu.wsgi.application"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ====================================================================
# Test runner
# ====================================================================
TEST_RUNNER = "core.test_runner.ProjectAppsDiscoverRunner"

# ====================================================================
# Database
# ====================================================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "kdu"),
        "USER": os.environ.get("POSTGRES_USER", "kdu"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "kdu"),
        "HOST": os.environ.get("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        "ATOMIC_REQUESTS": False,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Dili"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# ====================================================================
# Static / media
# ====================================================================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ====================================================================
# Django REST Framework
# ====================================================================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_PARSER_CLASSES": ("rest_framework.parsers.JSONParser",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "core.exceptions.drf_exception_handler",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "KDU Cooperative API",
    "DESCRIPTION": (
        "Enterprise Koperasi Core Banking & SHU Engine. "
        "Compliant with DL 16/2004 as amended by DL 76/2022."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/v1",
    "SORT_OPERATIONS": True,
    "TAGS": [
        {"name": "auth", "description": "JWT authentication"},
        {"name": "users", "description": "Current user profile"},
        {"name": "members", "description": "Member register"},
        {"name": "savings", "description": "Deposits and withdrawals"},
        {"name": "loans", "description": "Loan origination and repayment"},
        {"name": "expenses", "description": "Operating expenses"},
        {"name": "shu", "description": "Annual surplus distribution"},
        {"name": "governance", "description": "Global configuration"},
        {"name": "reports", "description": "Financial statements"},
        {"name": "pipeline", "description": "Maker-Checker-Certifier"},
        {"name": "dashboard", "description": "Dashboard aggregates"},
    ],
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,
        "displayOperationId": False,
    },
}

# ====================================================================
# JWT
# ====================================================================
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}


# ====================================================================
# CORS — allows the frontend origin to call the API
# ====================================================================
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "DJANGO_CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000,"
        "http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True


# ====================================================================
# CSRF trusted origins
# ====================================================================
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000,"
        "http://localhost:5173,http://127.0.0.1:5173",
    ).split(",")
    if origin.strip()
]
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
