# Generated by Django 5.0.14 on 2026-09-15 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0002_initial"),
        ("members", "0001_initial"),
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "principal_original",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "principal_outstanding",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("monthly_rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("term_months", models.PositiveIntegerField()),
                ("purpose", models.CharField(blank=True, max_length=255)),
                ("disbursed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("DISBURSED", "Disbursed"),
                            ("FULLY_REPAID", "Fully Repaid"),
                            ("WRITTEN_OFF", "Written Off"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans_disbursed",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="members.member",
                    ),
                ),
                (
                    "pipeline_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loans",
                        to="pipeline.transactionpipelineactor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanRepayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "principal_paid",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("interest_paid", models.DecimalField(decimal_places=2, max_digits=18)),
                ("payment_date", models.DateField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("SCHEDULED", "Scheduled")],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CHECK", "Pending Check"),
                            ("PENDING_CERTIFY", "Pending Certify"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_CHECK",
                        max_length=20,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_repayments",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repayments",
                        to="loans.loan",
                    ),
                ),
                (
                    "pipeline_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_repayments",
                        to="pipeline.transactionpipelineactor",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
    ]
