# Generated by Django 5.0.14 on 2026-09-15 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0002_initial"),
        ("members", "0001_initial"),
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShuFiscalYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year_start", models.DateField()),
                ("year_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "net_surplus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "kapital_sosial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "accumulated_reserva_legal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
            options={
                "ordering": ["-year_start"],
            },
        ),
        migrations.CreateModel(
            name="ShuMemberMonthlyBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month_date", models.DateField()),
                ("total_balance", models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name="ShuMemberPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jasa_simpanan_gross",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "jasa_bunga_gross",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("net_payout", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PAID", "Paid")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShuWeightingBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sum_weighted_balance",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("months_active", models.PositiveIntegerField()),
                (
                    "weighted_savings_units",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "loan_interest_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShuCalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("net_surplus", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "reserva_legal_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("admin_fund_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "jasa_simpanan_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("jasa_bunga_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "reserva_legal_amt",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "admin_fund_amt",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "jasa_simpanan_amt",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "jasa_bunga_amt",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_CHECK", "Pending Check"),
                            ("PENDING_CERTIFY", "Pending Certify"),
                            ("CERTIFIED", "Certified"),
                            ("PAYOUT_COMPLETE", "Payout Complete"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "pipeline_actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shu_calculations",
                        to="pipeline.transactionpipelineactor",
                    ),
                ),
                (
                    "reserve_journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shu_reserves",
                        to="ledger.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="shufiscalyear",
            constraint=models.CheckConstraint(
                check=models.Q(("year_end__gt", models.F("year_start"))),
                name="fy_end_after_start",
            ),
        ),
        migrations.AddField(
            model_name="shucalculation",
            name="fy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calculations",
                to="shu.shufiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="shumembermonthlybalance",
            name="fy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_balances",
                to="shu.shufiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="shumembermonthlybalance",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shu_monthly_balances",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="shumemberpayout",
            name="calc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to="shu.shucalculation",
            ),
        ),
        migrations.AddField(
            model_name="shumemberpayout",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shu_payouts",
                to="ledger.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="shumemberpayout",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shu_payouts",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="shuweightingbase",
            name="fy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weighting_base",
                to="shu.shufiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="shuweightingbase",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shu_weighting",
                to="members.member",
            ),
        ),
        migrations.AddIndex(
            model_name="shucalculation",
            index=models.Index(
                fields=["fy", "status"], name="shu_shucalc_fy_id_da5490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shumembermonthlybalance",
            index=models.Index(
                fields=["fy", "member"], name="shu_shumemb_fy_id_988119_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shumembermonthlybalance",
            constraint=models.UniqueConstraint(
                fields=("fy", "member", "month_date"), name="uq_shu_monthly"
            ),
        ),
        migrations.AddIndex(
            model_name="shumemberpayout",
            index=models.Index(
                fields=["calc", "status"], name="shu_shumemb_calc_id_24b282_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shumemberpayout",
            constraint=models.UniqueConstraint(
                fields=("calc", "member"), name="uq_shu_payout_per_member"
            ),
        ),
        migrations.AddIndex(
            model_name="shuweightingbase",
            index=models.Index(fields=["fy"], name="shu_shuweig_fy_id_e0a771_idx"),
        ),
        migrations.AddConstraint(
            model_name="shuweightingbase",
            constraint=models.UniqueConstraint(
                fields=("fy", "member"), name="uq_shu_weighting"
            ),
        ),
    ]
