# Generated by Django 5.0.14 on 2026-09-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shumemberpayout",
            name="annual_fee_deducted",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
