# Generated by Django 5.0.14 on 2026-09-15 04:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0001_initial"),
        ("pipeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "membership_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "salutation",
                    models.CharField(
                        choices=[
                            ("Mr", "Mr."),
                            ("Mrs", "Mrs."),
                            ("Ms", "Ms."),
                            ("Dr", "Dr."),
                            ("Prof", "Prof."),
                            ("Rev", "Rev."),
                        ],
                        default="Mr",
                        max_length=5,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("national_id", models.CharField(blank=True, max_length=20, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("date_of_birth", models.DateField()),
                ("aldeia", models.CharField(blank=True, max_length=100)),
                ("suco", models.CharField(blank=True, max_length=100)),
                ("posto", models.CharField(blank=True, max_length=100)),
                ("municipio", models.CharField(blank=True, max_length=100)),
                ("profession", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Active", "Active"),
                            ("Dormant", "Dormant"),
                            ("Suspended", "Suspended"),
                            ("Closed", "Closed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "kapital_sosial_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "date_joined",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("last_transaction_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["membership_number"],
            },
        ),
        migrations.CreateModel(
            name="MemberExitRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CHECK", "Pending Check"),
                            ("PENDING_CERTIFY", "Pending Certify"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_CHECK",
                        max_length=20,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_exits",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exit_requests",
                        to="members.member",
                    ),
                ),
                (
                    "pipeline_actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_exits",
                        to="pipeline.transactionpipelineactor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberOnboarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initial_capital_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CHECK", "Pending Check"),
                            ("PENDING_CERTIFY", "Pending Certify"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_CHECK",
                        max_length=20,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_onboardings",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="onboardings",
                        to="members.member",
                    ),
                ),
                (
                    "pipeline_actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_onboardings",
                        to="pipeline.transactionpipelineactor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["status", "last_transaction_at"],
                name="members_mem_status_6752b5_idx",
            ),
        ),
    ]
