# Generated by Django 5.0.14 on 2026-09-17 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_seed_member_sequence"),
        ("pipeline", "0003_alter_transactionpipelineactor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberexitrequest",
            name="pipeline_actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_exits",
                to="pipeline.transactionpipelineactor",
            ),
        ),
        migrations.AlterField(
            model_name="memberonboarding",
            name="pipeline_actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member_onboardings",
                to="pipeline.transactionpipelineactor",
            ),
        ),
    ]
