# Generated by Django 5.0.14 on 2026-10-01 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_memberexitrequest_pipeline_actor_and_more"),
        ("savings", "0002_alter_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="endorser_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="endorsed_as_first",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="endorser_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="endorsed_as_second",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="memberonboarding",
            name="entrance_fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="memberonboarding",
            name="first_month_savings_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="memberonboarding",
            name="obligatory_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_onboarding",
                to="savings.transaction",
            ),
        ),
    ]
