# Generated by Django 5.0.14 on 2026-09-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_seed_coa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["account_code"]},
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type", "status"], name="accounting__account_97c723_idx"
            ),
        ),
    ]
